// src/utils/icon-map.ts
import {
  // Basic Icons
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart,
  BarChart3,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Copy,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Globe,
  Grid,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  Layers,
  Link,
  Link2,
  Lock,
  Mail,
  Map,
  MapPin,
  Maximize,
  Menu,
  MessageSquare,
  Mic,
  Minimize,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Newspaper,
  Package,
  Paperclip,
  Pause,
  PenTool,
  Phone,
  PhoneCall,
  PieChart,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Star,
  Sun,
  Target,
  Terminal,
  ThumbsUp,
  TrendingUp,
  Truck,
  Users,
  Video,
  Volume2,
  Watch,
  Wifi,
  X,
  Zap,

  // Special Icons
  Award as Trophy,
  CalendarDays,
  CheckSquare,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleDollarSign,
  ClipboardCheck,
  CloudRain,
  Coffee,
  Compass,
  Cpu,
  CreditCard as Card,
  Crosshair,
  Crown,
  DownloadCloud,
  Eye as EyeIcon,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  Fingerprint,
  Flame,
  Gift,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe2,
  GraduationCap,
  HardDrive,
  Heart,
  Home as House,
  Key,
  Layers as Stack,
  Lightbulb,
  Link as Chain,
  List,
  Loader2,
  Lock as LockClosed,
  Map as MapIcon,
  Megaphone,
  MessageCircle,
  MicOff,
  Monitor,
  MousePointer,
  Package2,
  Palette,
  PieChart as ChartPie,
  Pin,
  Podcast,
  Printer,
  QrCode,
  Rocket,
  RotateCw,
  Rss,
  Scale,
  Scissors,
  ShieldAlert,
  ShieldOff,
  Smartphone,
  Speaker,
  Tag,
  Thermometer,
  ThumbsDown,
  Timer,
  Trash2,
  TrendingDown,
  Truck as TruckIcon,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  Users as Group,
  VideoOff,
  VolumeX,
  Wallet,
  WifiOff,
  Wind,
  XCircle,
  Youtube,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Github,
  Gitlab,
  Slack,
  Figma,
  Chrome,
  Codepen,
  Codesandbox,
  Dribbble,
  Facebook as FacebookIcon,
  Github as GithubIcon,
  Gitlab as GitlabIcon,
  Instagram as InstagramIcon,
  Linkedin as LinkedinIcon,
  Twitch,
  Twitter as TwitterIcon,
  Youtube as YoutubeIcon,
  Mail as MailIcon,
  MessageCircle as MessageCircleIcon,
  Phone as PhoneIcon,
  MapPin as MapPinIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  User as UserIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  LogOut,
  LogIn,
  UserPlus as UserPlusIcon,
  UserCheck as UserCheckIcon,
  UserX,
  Shield as ShieldIcon,
  Lock as LockIcon,
  Eye as EyeIcon2,
  EyeOff as EyeOffIcon,
  Bell as BellIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp as ThumbsUpIcon,
  Flag as FlagIcon,
  Bookmark,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Share as ShareIcon,
  Copy as CopyIcon,
  Edit as EditIcon,
  Trash2 as TrashIcon,
  Archive as ArchiveIcon,
  Filter as FilterIcon,
  Search as SearchIcon,
  X as XIcon,
  Plus as PlusIcon,
  Minus as MinusIcon,
  Check as CheckIcon,
  AlertCircle as AlertCircleIcon,
  Info as InfoIcon,
  HelpCircle as HelpCircleIcon,
  ExternalLink as ExternalLinkIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Menu as MenuIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  Grid as GridIcon,
  List as ListIcon,
  Layout,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Columns,
  Rows,
  Container,
  Box,
  Package as PackageIcon,
  Folder as FolderIcon,
  File as FileIcon,
  FileText as FileTextIcon,
  Image as ImageIcon,
  Film,
  Music,
  Headphones,
  Video as VideoIcon,
  Camera as CameraIcon,
  Mic as MicIcon,
  Volume2 as VolumeIcon,
  VolumeX as VolumeXIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  Activity as ActivityIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  BarChart as BarChartIcon,
  PieChart as PieChartIcon,
  LineChart,
  BarChart3 as BarChart3Icon,
  Target as TargetIcon,
  Award as AwardIcon,
  Trophy as TrophyIcon,
  Crown as CrownIcon,
  Star as StarIcon2,
  Heart as HeartIcon2,
  ThumbsUp as ThumbsUpIcon2,
  Flag as FlagIcon2,
  Bookmark as BookmarkIcon,
  Bell as BellIcon2,
  Calendar as CalendarIcon2,
  Clock as ClockIcon2,
  MapPin as MapPinIcon2,
  Navigation,
  Compass as CompassIcon,
  Globe as GlobeIcon,
  Map as MapIcon2,
  Layers as LayersIcon,
  Grid as GridIcon2,
  Layout as LayoutIcon,
  Sidebar as SidebarIcon,
  SidebarClose as SidebarCloseIcon,
  SidebarOpen as SidebarOpenIcon,
  PanelLeft as PanelLeftIcon,
  PanelRight as PanelRightIcon,
  PanelTop as PanelTopIcon,
  PanelBottom as PanelBottomIcon,
  Columns as ColumnsIcon,
  Rows as RowsIcon,
  Container as ContainerIcon,
  Box as BoxIcon,
  Package as PackageIcon2,
  Folder as FolderIcon2,
  File as FileIcon2,
  FileText as FileTextIcon2,
  Image as ImageIcon2,
  Film as FilmIcon,
  Music as MusicIcon,
  Headphones as HeadphonesIcon,
  Video as VideoIcon2,
  Camera as CameraIcon2,
  Mic as MicIcon2,
  Volume2 as VolumeIcon2,
  VolumeX as VolumeXIcon2,
  Play as PlayIcon2,
  Pause as PauseIcon2,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  Rewind as RewindIcon,
  FastForward as FastForwardIcon,
  Repeat as RepeatIcon,
  Shuffle as ShuffleIcon,
} from "lucide-react";

// Create icon map object
export const iconMap: Record<string, any> = {
  // Basic
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart,
  BarChart3,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Copy,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Globe,
  Grid,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  Layers,
  Link,
  Link2,
  Lock,
  Mail,
  Map,
  MapPin,
  Maximize,
  Menu,
  MessageSquare,
  Mic,
  Minimize,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Newspaper,
  Package,
  Paperclip,
  Pause,
  PenTool,
  Phone,
  PhoneCall,
  PieChart,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Star,
  Sun,
  Target,
  Terminal,
  ThumbsUp,
  TrendingUp,
  Truck,
  Users,
  Video,
  Volume2,
  Watch,
  Wifi,
  X,
  Zap,

  // Special
  Trophy,
  CalendarDays,
  CheckSquare,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleDollarSign,
  ClipboardCheck,
  CloudRain,
  Coffee,
  Compass,
  Cpu,
  Card,
  Crosshair,
  Crown,
  DownloadCloud,
  EyeIcon,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  Fingerprint,
  Flame,
  Gift,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe2,
  GraduationCap,
  HardDrive,
  Heart,
  House,
  Key,
  Stack,
  Lightbulb,
  Chain,
  List,
  Loader2,
  LockClosed,
  MapIcon,
  Megaphone,
  MessageCircle,
  MicOff,
  Monitor,
  MousePointer,
  Package2,
  Palette,
  ChartPie,
  Pin,
  Podcast,
  Printer,
  QrCode,
  Rocket,
  RotateCw,
  Rss,
  Scale,
  Scissors,
  ShieldAlert,
  ShieldOff,
  Smartphone,
  Speaker,
  Tag,
  Thermometer,
  ThumbsDown,
  Timer,
  Trash2,
  TrendingDown,
  TruckIcon,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  Group,
  VideoOff,
  VolumeX,
  Wallet,
  WifiOff,
  Wind,
  XCircle,

  // Social
  Youtube,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Github,
  Gitlab,
  Slack,
  Figma,
  Chrome,
  Codepen,
  Codesandbox,
  Dribbble,
  FacebookIcon,
  GithubIcon,
  GitlabIcon,
  InstagramIcon,
  LinkedinIcon,
  Twitch,
  TwitterIcon,
  YoutubeIcon,

  // Action Aliases
  MailIcon,
  MessageCircleIcon,
  PhoneIcon,
  MapPinIcon,
  ClockIcon,
  CalendarIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  LogOut,
  LogIn,
  UserPlusIcon,
  UserCheckIcon,
  UserX,
  ShieldIcon,
  LockIcon,
  EyeIcon2,
  EyeOffIcon,
  BellIcon,
  StarIcon,
  HeartIcon,
  ThumbsUpIcon,
  FlagIcon,
  Bookmark,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  CopyIcon,
  EditIcon,
  TrashIcon,
  ArchiveIcon,
  FilterIcon,
  SearchIcon,
  XIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  AlertCircleIcon,
  InfoIcon,
  HelpCircleIcon,
  ExternalLinkIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  MenuIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  GridIcon,
  ListIcon,
  Layout,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Columns,
  Rows,
  Container,
  Box,
  PackageIcon,
  FolderIcon,
  FileIcon,
  FileTextIcon,
  ImageIcon,
  Film,
  Music,
  Headphones,
  VideoIcon,
  CameraIcon,
  MicIcon,
  VolumeIcon,
  VolumeXIcon,
  PlayIcon,
  PauseIcon,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  ActivityIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  BarChartIcon,
  PieChartIcon,
  LineChart,
  BarChart3Icon,
  TargetIcon,
  AwardIcon,
  TrophyIcon,
  CrownIcon,
  StarIcon2,
  HeartIcon2,
  ThumbsUpIcon2,
  FlagIcon2,
  BookmarkIcon,
  BellIcon2,
  CalendarIcon2,
  ClockIcon2,
  MapPinIcon2,
  Navigation,
  CompassIcon,
  GlobeIcon,
  MapIcon2,
  LayersIcon,
  GridIcon2,
  LayoutIcon,
  SidebarIcon,
  SidebarCloseIcon,
  SidebarOpenIcon,
  PanelLeftIcon,
  PanelRightIcon,
  PanelTopIcon,
  PanelBottomIcon,
  ColumnsIcon,
  RowsIcon,
  ContainerIcon,
  BoxIcon,
  PackageIcon2,
  FolderIcon2,
  FileIcon2,
  FileTextIcon2,
  ImageIcon2,
  FilmIcon,
  MusicIcon,
  HeadphonesIcon,
  VideoIcon2,
  CameraIcon2,
  MicIcon2,
  VolumeIcon2,
  VolumeXIcon2,
  PlayIcon2,
  PauseIcon2,
  SkipBackIcon,
  SkipForwardIcon,
  RewindIcon,
  FastForwardIcon,
  RepeatIcon,
  ShuffleIcon,
};

// Helper function to get icon component
export function getIconComponent(iconName: string) {
  // Handle dot notation (e.g., "features.protection")
  const key = iconName.includes(".")
    ? iconName.split(".").pop() || iconName
    : iconName;

  // Handle kebab-case to PascalCase
  const pascalKey = key
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  const icon = iconMap[pascalKey] || iconMap[iconName] || iconMap.Newspaper;

  if (!icon) {
    console.warn(`Icon "${iconName}" not found. Using default.`);
    return iconMap.Newspaper;
  }

  return icon;
}

// Type for icon names
export type IconName = keyof typeof iconMap;
