// app/sitemap.ts
import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://tanzaniamedia.org";

  const routes = [
    "",
    "/about",
    "/about/leadership",
    "/about/network",
    "/about/financials",
    "/about/governance",
    "/about/annual-reports",
    "/about/awards",
    "/what-we-do",
    "/what-we-do/training",
    "/what-we-do/mentorship",
    "/what-we-do/digital-security",
    "/what-we-do/media-literacy",
    "/what-we-do/advocacy",
    "/what-we-do/research",
    "/what-we-do/legal-support",
    "/what-we-do/safety",
    "/impact",
    "/impact/stories",
    "/impact/dashboard",
    "/impact/grantees",
    "/impact/coverage",
    "/impact/case-studies",
    "/impact/trust-index",
    "/grants",
    "/grants/investigative",
    "/grants/community-media",
    "/grants/digital-innovation",
    "/grants/emergency-support",
    "/grants/women-in-media",
    "/grants/climate",
    "/resources",
    "/resources/toolkits",
    "/resources/research",
    "/resources/safety",
    "/resources/foi-templates",
    "/resources/policy-briefs",
    "/resources/white-papers",
    "/resources/annual-reviews",
    "/resources/research-reports",
    "/newsroom",
    "/get-involved",
    "/get-involved/donate",
    "/get-involved/partners",
    "/get-involved/corporate",
    "/get-involved/volunteer",
    "/get-involved/careers",
    "/get-involved/fellowships",
    "/contact",
    "/privacy",
    "/terms",
    "/cookies",
    "/accessibility",
    "/help-center",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1 : 0.8,
  }));
}
